title: My future blog
author: Taikozha Turdyakyn
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  You can learn about different things here, especially about having a strong personality

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
